# Generated by Django 4.2.2 on 2023-08-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ricevirequest',
            options={},
        ),
        migrations.AlterField(
            model_name='ricevirequest',
            name='contenuto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ricevirequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
