# Generated by Django 4.2.2 on 2024-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_ricevirequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracciaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('normalTime', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('operative_system', models.CharField(max_length=100)),
                ('page_name', models.CharField(default='impossibile identificare page', max_length=100)),
                ('city', models.CharField(default='impossibile identificare la citta', max_length=100)),
                ('region', models.CharField(default='impossibile identificare la regione', max_length=100)),
                ('country', models.CharField(default='impossibile identificare il paese', max_length=100)),
                ('type_method', models.CharField(default='impossibile identificare il metodo di richiesta', max_length=100)),
            ],
        ),
    ]
